# tell travis we need to have a copy of docker running
sudo: required
services:
  - docker

# build our image using Dockerfile.dev
before_install:
  - docker build -t acousineau/docker-react -f Dockerfile.dev .

# tell travis how to run our test suite
script:
  - docker run -e CI=true acousineau/docker-react yarn test -- --coverage

# tell travis how to deploy our code to AWS 
deploy:
  provider: elasticbeanstalk # travisCI has a base configuration for certain services (digital ocean, azure, aws)
  region: "us-east-1"
  app: "Docker React Tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-1-393102460116" # s3 bucket
  bucket_path: "Docker React Tutorial"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
